### ISSUE TITLE
Singleton `test` Runner apparently doesn't exist

### ISSUE THREAD

**Issue by ceilican** [propensive/probably#20]
Where can I find the singleton `test` runner mentioned in the ReadMe?

**Comment by odisseus** [comment]
The documentation might be outdated. Which version of Probably do you use?

**Comment by ceilican** [comment]
`0.4.0`, which is the version that I could find in "https://search.maven.org/search?q=probably".

But I also searched for the `test` singleton runner in the source code of the `master` branch here and I couldn't find it there either.

**Comment by propensive** [comment]
I'm not sure what happened, but the latest version has it, as `probably.global.test`.
