### ISSUE TITLE
Scala 3 Compatibility

### ISSUE THREAD

**Issue by ceilican** [propensive/probably#22]
I see that there is a `scala3` branch. Is the version in that branch compilable with the current version of dotty?

**Comment by arnolddevos** [comment]
Hi John, here is a minimalist take on probably for scala 3.  Just for interest.  https://github.com/arnolddevos/epsilonio/blob/master/src/test/scala/probably.scala

**Comment by arnolddevos** [comment]
BTW I think that part of the probably DSL that relies on structural types will have to go.
