### ISSUE TITLE
Show time units in output

### ISSUE THREAD

**Issue by propensive** [propensive/probably#29]
The report shows the timings of each test without any units, and these should be shown. The same units should be used for every test in the report (or at least in the same suite). Test times are currently measured in milliseconds (using `System.currentTimeMillis` though, it would make sense to display them in either `ms` or `s`. However, it may also be worthwhile recording `System.nanoTime` *as well* to report times in `µs` or `ns` if all the tests in the suite are "fast".

Tests should be added to the report to check this output.

**Comment by wi101** [comment]
Will give it a try
