### ISSUE TITLE
Exceptions thrown by the tests are hidden

### ISSUE THREAD

**Issue by odisseus** [propensive/probably#9]
### Steps to reproduce
1. Create a [Fury](https://github.com/propensive/fury) build with an application module that depends on `probably`.
2. Create a main class that extends `TestApp`.
3. Create a test that always throws an exception, e. g. `???`
4. Build the module to run the test.

**Expected behaviour:** The error message and the stack trace are printed to stdout.
**Actual behaviour:** Neither the error message nor the stack trace is printed; the test is marked as failed in the test report.

Unless the test has side effects (such as `println`), this situation is indistinguishable from a failed assertion.

**Comment by propensive** [comment]
Fixed with the rewrite.
